# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.hbs'
        tags: |
          $(tag)
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: push an image
      inputs:
        command: push
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.hbs'
        tags: |
          $(tag)
- stage: kubesetups
  displayName: Kubedrop
  jobs:
    - job: kubernatesinstallandCopyartifacts
      displayName: Push
      steps:
      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest'
    
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          command: 'apply'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureContainerRegistry: 'ecomercestore.azurecr.io'
    
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'FilePath'
          TargetPath: 'helm'
     